# .goreleaser.yml
build:
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w
    - -X "main.Version={{ .Version }}"
  flags:
    - -trimpath

archives:
  -
    format: binary

release:
  prerelease: auto

changelog:
  filters:
    exclude:
      - "^Merge branch"
